version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    environment:
      - SERVER_PORT=8501
      - SERVER_ADDRESS=0.0.0.0
      - GOOGLE_APPLICATION_CREDENTIALS=./credential.json
